version: '3'

volumes:
    postgres:
        driver: local

services:
    api:
        build:
            context: .
            dockerfile: api.dockerfile
        command: ["./wait-for-it.sh", "db", "python", "app/manage.py", "runserver", "0.0.0.0:8000"]
        volumes:
            - ./env/:/env
            - ./api/:/code
        env_file:
            - ./env/.env
        ports:
            - "8000:8000"
        depends_on:
            - db
    app:
        build:
            context: .
            dockerfile: app.dockerfile
        ports:
            - "80:8080"
        volumes:
            - ./env/:/env
            - "./app:/app/"
        command:  >
            sh -c "yarn install && yarn serve"
        depends_on:
            - db
    db:
        image: postgres:latest
        volumes:
            - ./.data_postgres/:/data/postgres
        ports:
            - "5432:5432"
        env_file:
            - ./env/.env